### ISSUE TITLE
Palindrome Flipping : CODECHEF STARTERS 60 SOLUTION IN C++

### ISSUE THREAD

**Issue by sahilsrivastava25** [Shubhamlmp/Programming-Practice#176]
I would like to contribute this problem in the your repository. Also I will be really grateful to you if you tag this as Hacktoberfest 2022 contribution.

**Comment by daxshonly** [comment]
bro , i just send you the PR for the solution of palindrome flipping ,
so you can check and merge it into your repo .
thanks \
happy coding
