### ISSUE TITLE
Add optimized solution for the problems in your favorite programming language

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#2]
1. Add optimized solution for the problems in your favorite programming language.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like FooBar,FooBarTest.
4. Add solution link in readme file with language category in solution section like C, C++, Java, Javascript, Python.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by harsitagarwalla187** [comment]
Can you assign me this issue?

**Comment by aditya-agr** [comment]
Can I work on this ?

**Comment by bandevedant** [comment]
please assign this to me

**Comment by Aly838** [comment]
Please  assign me this issue

**Comment by Tushar161101** [comment]
Hey!
I'm Hacktoberfest'22 contributor .I would like to work on this issue. Please assign me this issue.

**Comment by AnishKumarGarg** [comment]
pls assign me this
