### ISSUE TITLE
add projects which will help to beginners

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#245]
**Any project will be accepted which will follow the below instructions.**

1. we are not expecting any large project.
2. Any beginner level project will be accepted.
3. project will be implemented in any language.

**Rules related to PR:**

- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by vanshikaa-agarwal** [comment]
I would like to work on this

**Comment by Shubhamlmp** [comment]
> I would like to work on this

Okay you can start contributing @vanshikaa-agarwal

**Comment by vanshikaa-agarwal** [comment]
I made a color flipper...using simple Html,css,and js...should i create a pr for it

**Comment by Shubhamlmp** [comment]
> I made a color flipper...using simple Html,css,and js...should i create a pr for it

@vanshikaa-agarwal Great, yes you can.

**Comment by Ashish93-mrx** [comment]
i would like to add python beginner project in this issue,please assign me.
