### ISSUE TITLE
implement beginner project in Javascript

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#273]
**Any project will be accepted which will follow the below instructions.**
1. we are not expecting any large project, small project is Okay.
2. Any beginner level project will be accepted.
3. project will be implemented in Javascript language.

**Rules related to PR:**
- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by Zweak** [comment]
Hey @Shubhamlmp, Can you assign me? 
I'd like working on a beginner friendly javascript project.

**Comment by Shubhamlmp** [comment]
> Hey @Shubhamlmp, Can you assign me? I'd like working on a beginner friendly javascript project.

@Zweak  Assigned
Thank You.
