### ISSUE TITLE
implement beginner project in python

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#274]
**Any project will be accepted which will follow the below instructions.**
1. we are not expecting any large project small project is Okay.
2. Any beginner level project will be accepted.
3. project will be implemented in python language.

**Rules related to PR:**
- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by varun-jaiswal17** [comment]
@Shubhamlmp please assign this to me.
thanks.

**Comment by Shubhamlmp** [comment]
> @Shubhamlmp please assign this to me. thanks.

@vrooomy Assigned
Thank You.

**Comment by HuzaifaChaudary** [comment]
Pls assign me this . The fact that Shubham is the only maintainer that is active and his repository 's PRs are really from humans instead of bots. I wanna do my second PR into ur Repo. Giving you 🥇
