### ISSUE TITLE
implement beginner project in C

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#275]
**Any project will be accepted which will follow the below instructions.**
1. we are not expecting any large project small project is Okay.
2. Any beginner level project will be accepted.
3. project will be implemented in C language.

**Rules related to PR:**
- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by Mayureshkaulwar** [comment]
assign to me

**Comment by voiDXDops** [comment]
Can I have the access to do this project?

**Comment by Shubhamlmp** [comment]
> Can I have the access to do this project?

@voiDXDops You can work on any issue whatever you like
