### ISSUE TITLE
implement beginner project in C++

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#276]
**Any project will be accepted which will follow the below instructions.**
1. we are not expecting any large project small project is Okay.
2. Any beginner level project will be accepted.
3. project will be implemented in C++ language.

**Rules related to PR:**
- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by debjitnandan05** [comment]
I want to add my C++ project to your repository. Can you please assign me this task?

**Comment by Shubhamlmp** [comment]
@debjitnandan05 assigned

**Comment by HuzaifaChaudary** [comment]
hey! I want to add my C++ project to your repository. Can you please assign me this task?

**Comment by somyashri3** [comment]
hey @Shubhamlmp, I would like to contribute to this issue
