### ISSUE TITLE
implement project under 100 lines of code (any language)

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#278]
**Any project will be accepted which will follow the below instructions.**
1. we are not expecting any large project small project is Okay.
2. Any beginner level project will be accepted.
3. project will be implemented in any language.

**Rules related to PR:**
- create new directory (folder) with your project name that include below details.
- code with well explained with comments
- add instructions in documentation how someone run that project.
- add output of your project

**Comment by Mayureshkaulwar** [comment]
assign to me
