### ISSUE TITLE
Solved any Unsolved Problem and get PR accepted for Hacktoberfest 2022

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#279]
In Our repository there are lot of problems left which are unsolved,
So, what you have to do solve unsolved problems and get PR accepted for Hacktoberfest 2022

**How to know which problem is Unsolved**

- Go to our readme section.
- There is a column for solution and check

**Comment by thesuaveguy** [comment]
hi @Shubhamlmp ,could you please review my pr

**Comment by shreya2663** [comment]
can i do it

**Comment by ya332** [comment]
Hello, please review my 4 PRs:
1) https://github.com/Shubhamlmp/Programming-Practice/pull/306
2) https://github.com/Shubhamlmp/Programming-Practice/pull/307
3) https://github.com/Shubhamlmp/Programming-Practice/pull/308
4) https://github.com/Shubhamlmp/Programming-Practice/pull/309

Thanks.
