### ISSUE TITLE
Add optimized solution for the problems in C++

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#3]
1. Add optimized solution for the problems in **C++**.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like **FooBar,FooBarTest**.
4. Add solution link in readme file with **C++** language category in solution section.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by ajju-1209** [comment]
I can add solutions in cpp , can you assign this to me?

**Comment by aanchalsharmaa1024** [comment]
I can do it @Shubhamlmp plz assign it to me . I will do it with proper comments

**Comment by Shubhamlmp** [comment]
> I can add solutions in cpp , can you assign this to me?

Hi @aanchalsharmaa1024, first you have to fork project,
And give star to the project.

And after that start contributing.
Thank you!

**Comment by Shubhamlmp** [comment]
> I can add solutions in cpp , can you assign this to me?

Hi @ajju-1209, first you have to fork project,
And give star to the project.

And after that start contributing.
Thank you!

**Comment by harsitagarwalla187** [comment]
Can  Everyone work in this issue?

**Comment by Shubhamlmp** [comment]
> Can Everyone work in this issue?

Yes, @harsitagarwalla187

**Comment by Ashpreetwadhwa** [comment]
i am interested in this task @Shubhamlmp

**Comment by Shubhamlmp** [comment]
> i am interested in this task @Shubhamlmp

Okay no issues follow the rules and start working

**Comment by daxshonly** [comment]
can i also contribute in this project ??

**Comment by Ashpreetwadhwa** [comment]
> > i am interested in this task @Shubhamlmp
> 
> Okay no issues follow the rules and start working 

Ok just assign me this task

**Comment by Shubhamlmp** [comment]
> can i also contribute in this project ??

@imdarshansingh yes you can, follow the rules and start working.

**Comment by sahiljarngal** [comment]
hi, I am also contribute in this project. Please assign me @Shubhamlmp

**Comment by starrohan999** [comment]
I can also add C++ solutions for most of the questions. @Shubhamlmp  please assign it to me.

**Comment by starrohan999** [comment]
@Shubhamlmp 
LGTM!

**Comment by AditiBanik** [comment]
hello, i have another cpp problem solution from leetcode , i have created pr request, kindly please look into it and merge it. Thank you.

**Comment by AditiBanik** [comment]
hello, i have another cpp problem solution from leetcode , i have created pr request, kindly please look into it and merge it. Thank you. kindly please assign me this issue

**Comment by daxshonly** [comment]
Hello @Shubhamlmp  i have added some optimized code , so if you like it then merge it .
Thanks 
happy coding
