### ISSUE TITLE
Correct table format in readme file

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#35]
correct the table format in readme file for correct format check Data Type & Conditions format.

1. Add counting for quesions under `#`
2. Add problem name under under title section and add problem link for each problem

**Comment by ProtyayMnd50** [comment]
can you assign me this @Shubhamlmp ?

**Comment by Shubhamlmp** [comment]
> can you assign me this @Shubhamlmp ?

@ProtyayMnd50 first forked repository and give star to it.
and start working on it by creating your own branch.

**Comment by Shubhamlmp** [comment]
@ProtyayMnd50 are you working on this ticket or not?

**Comment by ProtyayMnd50** [comment]
Sorry for the reply @Shubhamlmp I am sure working on it

**Comment by Shubhamlmp** [comment]
> Sorry for the reply @Shubhamlmp I am sure working on it

Okay do it fast

**Comment by ProtyayMnd50** [comment]
@Shubhamlmp you have merged my pr sir

**Comment by Shubhamlmp** [comment]
@ProtyayMnd50  are you doing or I assign this task to someone else?

**Comment by ProtyayMnd50** [comment]
Doing it @Shubhamlmp

**Comment by ProtyayMnd50** [comment]
Hey @Shubhamlmp I have made another fresh pull request pls review it. And really sorry for the delay.
