### ISSUE TITLE
Add optimized solution for the problems in C

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#4]
1. Add optimized solution for the problems in **C**.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like **FooBar,FooBarTest**.
4. Add solution link in readme file with **C** language category in solution section.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by Aman0307** [comment]
@Shubhamlmp I would like to contribute to this.

**Comment by Shubhamlmp** [comment]
> @Shubhamlmp I would like to contribute to this.

@Aman0307 Okay,
first fork the repository and start working on it

**Comment by Aman0307** [comment]
@Shubhamlmp I have created a PR. Please merge.
