### ISSUE TITLE
Add optimized solution for the problems in Java

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#5]
1. Add optimized solution for the problems in **Java**.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like **FooBar,FooBarTest**.
4. Add solution link in readme file with **Java** language category in solution section.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by Ashpreetwadhwa** [comment]
Hey @Shubhamlmp i am interested in this task

**Comment by Shubhamlmp** [comment]
Hi @Ashpreetwadhwa you can start working on the problems which you are able to solve.

Follow this:
1. fork the repository and give ⭐ to the project
2. Create your own branch from master
3. Always update your feature branch when start working on new problem
4. Then push the code and create merge request
