### ISSUE TITLE
Add optimized solution for the problems in Python

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#6]
1. Add optimized solution for the problems in **Python**.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like **FooBar,FooBarTest**.
4. Add solution link in readme file with **Python** language category in solution section.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by rhymasharma** [comment]
Hey, I want to contribute to this repo. Could you please elaborate which problems are being referred?

**Comment by Shubhamlmp** [comment]
> Hey, I want to contribute to this repo. Could you please elaborate which problems are being referred?

Hey @rhymasharma, You can solve any problems of your choice which you are able to solve.

and make sure you read all rules before contributing to the project.

**Comment by Ashpreetwadhwa** [comment]
hey @Shubhamlmp i am interested in this task

**Comment by Shubhamlmp** [comment]
> hey @Shubhamlmp i am interested in this task

@Ashpreetwadhwa, Okay you can work on this first forked repos and give a star to it.
and start working on it

**Comment by Ashpreetwadhwa** [comment]
Hey@Shubhamlmp  just assign me this task

**Comment by AnishKumarGarg** [comment]
hey i want to contribute pls assign me this issue
