### ISSUE TITLE
Add optimized solution for the problems in Javascript

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#7]
1. Add optimized solution for the problems in **Javascript**.
2. Add comment and explain each and every line.
3. Variable name should be meaningful and in camelCase like **FooBar,FooBarTest.**
4. Add solution link in readme file with **Javascript** language category in solution section.
5. Your Code must be pretty formated.
6. Have a good commit message.

**Comment by samarthkumar008** [comment]
Hey, I want to contribute to this repo.please referred me?

**Comment by Shubhamlmp** [comment]
> Hey, I want to contribute to this repo.please referred me?

@Akkichau Okay you can start working on it
