### ISSUE TITLE
Question numbers in Readme can be made better

### ISSUE THREAD

**Issue by manish-9245** [Shubhamlmp/Programming-Practice#74]
Instead of implementing an overall count, you can choose to have a sectional serial number.
This would enable new contributors and add the question in the readme.md directly and won't have to change all the question numbers ahead of it.

**Comment by ProtyayMnd50** [comment]
Can you assign it to me @manish-9245 ?

**Comment by Shubhamlmp** [comment]
> Can you assign it to me @manish-9245 ?

@manish-9245  Okay you do it
