### ISSUE TITLE
Correct table format in readme file

### ISSUE THREAD

**Issue by Shubhamlmp** [Shubhamlmp/Programming-Practice#9]
correct the table format in readme file for correct format check **Data Type & Conditions** format.

1. Add counting for quesions
2. remove extra `\` from rows

**Comment by aanchalsharmaa1024** [comment]
@Shubhamlmp .plz assign it to me . I can do it

**Comment by prashantpadhy** [comment]
assign me this task

**Comment by Shubhamlmp** [comment]
> assign me this task

Hi @prashantpadhy, first go through the rules.

**Comment by prashantpadhy** [comment]
yes forked

> Hi @prashantpadhy, first go through the rules.
yes forked and stared

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by Shivani622** [comment]
@prashantpadhy  I want to work on this issue .

**Comment by Shubhamlmp** [comment]
> @prashantpadhy I want to work on this issue .

Hi @Shivani622, can you please look at another tasks.

**Comment by Shubhamlmp** [comment]
> Can i work in this issue?

Hi @harsitagarwalla187  can you please look at another tasks.

**Comment by Shubhamlmp** [comment]
> yes forked
> 
> > Hi @prashantpadhy, first go through the rules.
> > yes forked and stared

Okay, can you please look at another tasks.

**Comment by prashantpadhy** [comment]
done
