### ISSUE TITLE
Can Add Maximum-subarray problem in Array Section(Kadane's Algo)

### ISSUE THREAD

**Issue by starrohan999** [Shubhamlmp/Programming-Practice#90]
Kadane's Algo was asked most of the MNCs in their interview round and this is the best approach to solve the question.
@Shubhamlmp 
please assign this to me so that I can start working on this.
LGTM!

**Comment by starrohan999** [comment]
Looking forward to learning and contribute @Shubhamlmp

**Comment by Shubhamlmp** [comment]
> Kadane's Algo was asked most of the MNCs in their interview round and this is the best approach to solve the question. @Shubhamlmp please assign this to me so that I can start working on this. LGTM!

@starrohan999 currently I'm focusing on only beginner's level problems, after completing this we start working on algorithms part
